USE [master]
GO

/****** Object:  Database [LostIdentity]    Script Date: 5/06/2018 7:19:30 PM ******/
CREATE DATABASE [LostIdentity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LostIdentity', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\LostIdentity.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LostIdentity_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\LostIdentity_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LostIdentity] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LostIdentity].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LostIdentity] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LostIdentity] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LostIdentity] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LostIdentity] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LostIdentity] SET ARITHABORT OFF 
GO

ALTER DATABASE [LostIdentity] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LostIdentity] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LostIdentity] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LostIdentity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LostIdentity] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LostIdentity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LostIdentity] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LostIdentity] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LostIdentity] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LostIdentity] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LostIdentity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LostIdentity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LostIdentity] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LostIdentity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LostIdentity] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LostIdentity] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LostIdentity] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LostIdentity] SET RECOVERY FULL 
GO

ALTER DATABASE [LostIdentity] SET  MULTI_USER 
GO

ALTER DATABASE [LostIdentity] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LostIdentity] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LostIdentity] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LostIdentity] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LostIdentity] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LostIdentity] SET  READ_WRITE 
GO


